###
POST http://localhost:4000/movies
Content-Type: application/json

{
    "title": "Dracula",
    "description": "pelicula de vampiros",
    "year": 1950
}

###
PUT http://localhost:4000/movies/2
Content-Type: application/json

{
    "year": 1990
}

###
DELETE http://localhost:4000/movies/1